### ISSUE TITLE
Release 

### ISSUE THREAD

**Issue by chrismcv** [brunch/commonjs-require-definition#9]
Hi, been meaning to ask for a release to npm of this version for a long time.  Would you mind doing that at some point?
Thanks, 
Chris

**Comment by kruppel** [comment]
@paulmillr I'd also like to get a formal bump, if possible. v0.1.2 in particular cannot be compressed with yuicompressor 2.4.8 (fixed with 9db8902019b14a574662d10ff389f3767fe9cbc3) due to the comment being detected as an informal parameter. Easy enough to target a commit or remove the comment, but it'd be even better if the latest were published. Thanks!

**Comment by kruppel** [comment]
Thanks @paulmillr !
